services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URI=postgres://postgres:pass@db:5432/data?sslmode=disable
      - REDIS_URI=redis:6379
      - ACCESS_TOKEN_PRIVATE_KEY=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT2dJQkFBSkJBTXlhTEl2ekpjTGRuR1RUQ0QrSWNrK2dPUU5TT2dWNFovYTg0bm1nN1lJUjZPTGJaTkQ5Cm1QRExmV0o2TmFUN2pTeTllU1VWU3ZrMHluL2pvZjZvWklzQ0F3RUFBUUpBV3dlRkprYnAyQWNORy9hZ1J0UUkKTjlFTFRLVDYxNUE0Z1JpTWtweTh6dzhvb3FBQVZmWUwybGkvZjZTZTdyNkZCL05iWFdadm45dG41ZW9hWjQ5agpvUUloQVBZNE4wUGtHT1ZqNWtudkxDVjVPeXYwaFdaVUl4Zm82K1RlbFdTOWZ0UDVBaUVBMUxyQlVsYVFKMndOCnc4azlkdUhMc0tlWWRyQWhEb21LcU5QWGhFU2tGYU1DSUFtQVY5bWQxcndiWThxY21TYUZEQnlCSGhpNXpIVGkKdngrZzIwRDg4d1Q1QWlFQXEvcmJ4ZXhUbUh0ajJXLzlML28xeVhpRTZ4ZFRja1JDQkdGWGNBaHFPMDhDSUJHKwpoc1hXaCt6TzVEQ1dFQVN0NWJSemh0NkhvaUJsL0RWKzY5cHRKalNtCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
      - ACCESS_TOKEN_PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBTXlhTEl2ekpjTGRuR1RUQ0QrSWNrK2dPUU5TT2dWNApaL2E4NG5tZzdZSVI2T0xiWk5EOW1QRExmV0o2TmFUN2pTeTllU1VWU3ZrMHluL2pvZjZvWklzQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
      - ACCESS_TOKEN_EXPIRED_IN=15m
      - ACCESS_TOKEN_MAXAGE=15
      - REFRESH_TOKEN_PRIVATE_KEY=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT0FJQkFBSkFaUmNBdVE5RzFtUThoQ3o3YldYMHZBTHEySFI2Zzh1MlM3Q094NVdXcUR2THJBRmRxeGpDCmlValQzVmRPaVhvVXN5U2pySENCbTNpTzRCN3U2eUlTRVFJREFRQUJBa0FNaXIwUk9MNytMSE9CcHA4UEpKNG4Ka1drWHIrUGZaQy9hMWkzd3Z6Tnc3Y3BZMnR3d3dSaVczOVcraXA1NU5kYkxVeXRaNFJwa1BvWEtjSktlTUF2QgpBaUVBcGFCWEhFQ1RZcVgrM3BNTUdwbnB4TlNLSmFieXFJd1NVQmNFNm5idG4xa0NJUUNjUDlRSXNYcFlITFFDCmdIZVFZU1pWMEtBallFOVdPenA3RkZhSFY2Q3BlUUlnUGQzR3JDYnk1c1phallrZjNFL2hva1JCMWc2bVZZNzgKeUMzUkNFT2tQd0VDSUgrc1RDYTZWcjBPM3l3NEt2cW4xM3BCbWNpdVZzV2dhZjNPTlpJcjBSVUpBaUFBdGszMwpiNDhoaW84NmFjM014dXhQc0EyRHY3MDAzYUpuVnlkMkg4a3FIdz09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
      - REFRESH_TOKEN_PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZzd0RRWUpLb1pJaHZjTkFRRUJCUUFEU2dBd1J3SkFaUmNBdVE5RzFtUThoQ3o3YldYMHZBTHEySFI2Zzh1MgpTN0NPeDVXV3FEdkxyQUZkcXhqQ2lValQzVmRPaVhvVXN5U2pySENCbTNpTzRCN3U2eUlTRVFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t
      - REFRESH_TOKEN_EXPIRED_IN=60m
      - REFRESH_TOKEN_MAXAGE=60
    depends_on:
       db:
         condition: service_healthy
       redis:
         condition: service_healthy
  db:
     image: postgres
     restart: always
     user: postgres
     volumes:
       - progresDB:/var/lib/postgresql/data
     environment:
       - POSTGRES_DB=data
       - POSTGRES_PASSWORD=pass
     expose:
       - 5432
     healthcheck:
       test: [ "CMD", "pg_isready" ]
       interval: 10s
       timeout: 5s
       retries: 5
  redis:
      image: redis:alpine
      restart: always
      container_name: redis
      expose:
        - 6379
      volumes:
        - redisDB:/data
      healthcheck:
        test:  ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5
  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.18.0
    restart: no
    depends_on:
      db:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgres://postgres:pass@db:5432/data?sslmode=disable
      - GOOSE_VERBOSE=true
    volumes:
      - ./db/migrations:/migrations
volumes:
  progresDB:
  redisDB:

