services:
  db:
     image: postgres
     user: postgres
     environment:
       - POSTGRES_DB=data
       - POSTGRES_PASSWORD=pass
     ports:
       - 5432:5432
     volumes:
       - progresDB:/var/lib/postgresql/data
  redis:
      image: redis:alpine
      container_name: redis
      ports:
        - 6379:6379
      volumes:
        - redisDB:/data
volumes:
  progresDB:
  redisDB:

